#!/usr/bin/env bash
# version 1.0.0
# Author: Steve Magnuson, AG7GN
#
# This script installs various scripts and configuration files used to make the 
# RaspiOS into the Nexus DR-X

sudo cp -f nexus-bootstrap/usr/local/sbin/* /usr/local/sbin/

#######################################################################
## Add cronjob to check for presence of DO_NOT_DELETE_THIS_FILE
WHO="$USER"
WHEN="@reboot"
WHAT="sleep 5 && /usr/local/sbin/initialize-pi.sh"
JOB="$WHEN $WHAT"
cat <(fgrep -i -v "$WHAT" <(sudo crontab -u $WHO -l)) <(echo "$JOB") | sudo crontab -u $WHO -

#######################################################################
## Shutdown button
sudo cp -f nexus-bootstrap/etc/systemd/system/* /etc/systemd/system/
sudo systemctl daemon-reload
sudo systemctl enable shutdown_button.service
sudo systemctl start shutdown_button.service

#######################################################################
## Check piano switch at startup
AUTOSTART="/etc/xdg/lxsession/LXDE-pi/autostart"
if [[ -s $AUTOSTART ]] 
then
	if ! grep -q check-piano.sh $AUTOSTART 2>/dev/null
	then
		sudo sed -i '/@pcmanfm .*/a @bash \/usr\/local\/sbin\/check-piano.sh' $AUTOSTART
	fi
fi

#######################################################################
## Desktop background
cp nexus-bootstrap/Pictures/*.jpg $HOME/Pictures/
mkdir -p $HOME/.config/pcmanfm/LXDE-pi
cp nexus-bootstrap/config/pcmanfm/LXDE-pi/desktop-items-0.conf $HOME/.config/pcmanfm/LXDE-pi/
pcmanfm --reconfigure

#######################################################################
## Modify Log Management
sed -n "/#### RULES ####/q;p" /etc/rsyslog.conf > /tmp/rsyslog.conf
cat nexus-bootstrap/etc/rsyslog.conf.excerpt >> /tmp/rsyslog.conf 
sudo cp -f /etc/rsyslog.conf /etc/rsyslog.conf.backup
sudo cp -f /tmp/rsyslog.conf /etc/rsyslog.conf
sudo rm -f /var/log/debug*
sudo cp -f /etc/logrotate.conf /etc/logrotate.conf.backup
if grep -qE "^#compress" /etc/logrotate.conf
then
	sudo sed -i -e "s/^#compress.*/compress/" /etc/logrotate.conf
	sudo sed -i "/^compress/a compresscmd \/bin\/bzip2\nuncompresscmd \/bin\/bunzip2\ncompressoptions -9\ncompressext .bz2" /etc/logrotate.conf
fi

if ! grep -qf "$LOCAL_GIT_REPO_DIR/nexus-bootstrap/etc/logrotate.d/rsyslog" /etc/logrotate.d/rsyslog
then
	sudo cp -f /etc/logrotate.d/rsyslog /etc/logrotate.d/rsyslog.backup
	cat "$LOCAL_GIT_REPO_DIR/nexus-bootstrap/etc/logrotate.d/rsyslog" > /tmp/rsyslog
	cat /etc/logrotate.d/rsyslog >> /tmp/rsyslog
	sudo cp -f /tmp/rsyslog /etc/logrotate.d/rsyslog
	sudo systemctl restart rsyslog
fi

#######################################################################
## Make .vimrc file
if [[ ! -s $HOME/.vimrc ]]
then
	cp -f nexus-bootstrap/vimrc $HOME/.vimrc
fi

#######################################################################
## Make .vimrc file


